### ISSUE TITLE
乐于助人也是错，呵呵

### ISSUE THREAD

**Issue by xflxfl** [wuand/wuand#2]
F4ck Off

**Comment by taotao2010** [comment]
ip.cn是内置的debug页面，通过该页面的状态，能够判断出用户此时的情况
只有这一个网站可以用，因为是规则里指定的
另外，github不讨论管理策略，我无条件支持各位管理员

**Comment by xflxfl** [comment]
是的，已经没必要讨论，我已经退群了。
就因为我发的网站不支持debug页面，然后就无缘无故被T了。真可笑。

送你3个字，权 限 狗。
