### ISSUE TITLE
CentOS下shadowsocks-libev一键安装脚本

### ISSUE THREAD

**Issue by taotao2010** [wuand/wuand#7]
适用于：CentOS 6&7

wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev.sh
chmod +x shadowsocks-libev.sh
./shadowsocks-libev.sh 2>&1 | tee shadowsocks-libev.log

启动：/etc/init.d/shadowsocks start
停止：/etc/init.d/shadowsocks stop
重启：/etc/init.d/shadowsocks restart
查看状态：/etc/init.d/shadowsocks status
修改配置：vi /etc/shadowsocks-libev/config.json
卸载：./shadowsocks-libev.sh uninstall

转自：https://teddysun.com/357.html

**Comment by snower1314** [comment]
Got it
